version: "3.8"

services:
  server:
    build: .
    ports:
      - "3500:3500"
    environment:
      - NODE_ENV=development
      - PORT=3500
      - MONGO_URI=mongodb://mongo:27017/episode-namer
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

volumes:
  mongo_data:
